version: '2'

services:
  app:
    build: .
    command: run.py 
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:latest
  redis:
    image: redis:latest
