version: '2'

services:
  app:
    build: .
    command: python run.py 
    volumes:
      - .:/code
    links:
      - mongo
      - redis
  mongo:
    image: mongo:latest
    expose:
      - "27017"
  redis:
    image: redis:latest
    expose: 
      - "6379"
